package net.xiidea.enginx.domain.deployment;

import net.xiidea.enginx.domain.proxy.HeaderDirection;
import net.xiidea.enginx.domain.proxy.LoadBalancingMethod;
import net.xiidea.enginx.domain.proxy.LocationMatchType;
import net.xiidea.enginx.domain.proxy.LocationRule;
import net.xiidea.enginx.domain.proxy.ProxySite;
import net.xiidea.enginx.domain.proxy.ProxySiteHeader;
import net.xiidea.enginx.domain.proxy.ProxySiteSpec;
import net.xiidea.enginx.domain.proxy.UpstreamTarget;
import net.xiidea.enginx.domain.shared.ValidationException;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;

/**
 * Turns validated site definitions into NGINX configuration.
 *
 * <p>A pure function, deliberately. Given the same sites it produces byte-identical output, which
 * is what makes the content hash meaningful: two renders that agree are the same configuration,
 * so a redeploy of unchanged state is detectably a no-op. It also means the whole renderer can be
 * tested against golden files with no database, no container and no NGINX.
 *
 * <p>Nothing here escapes user input, because nothing here receives unescaped input. Every value
 * that reaches this class has already passed through a value object whose constructor rejects the
 * characters that could terminate a directive, open a block, or interpolate a variable. Escaping
 * at render time would be a second line of defence guarding a door that is already locked, and
 * would invite the belief that unvalidated values are safe to pass in.
 */
public final class NginxConfigRenderer {

    private static final String GENERATED_BY = "Easy NGINX Admin";
    // Loaded first: NGINX reads conf.d/*.conf in filename order, and the default server has to
    // exist before the site blocks for the intent to be obvious to anyone reading the tree.
    private static final String BASE_FILE = "conf.d/00-enginx-base.conf";

    /**
     * Where the agent stages HTTP-01 challenge responses.
     *
     * <p>Outside the release tree deliberately. A token has to appear within seconds and is
     * discarded just as quickly; routing it through a bundle would mean a full
     * render-validate-activate-reload cycle to publish it and another to remove it, twice for
     * every certificate, churning the real configuration each time.
     */
    private static final String ACME_CHALLENGE_ROOT = "/etc/nginx/enginx/acme-challenge/";

    /**
     * The certificate the HTTPS catch-all presents. Generated by the agent, outside the release
     * tree, and deliberately valid for no name at all — see the catch-all comment below.
     */
    private static final String DEFAULT_TLS_CERT = "/etc/nginx/enginx/default-tls/default.crt";
    private static final String DEFAULT_TLS_KEY = "/etc/nginx/enginx/default-tls/default.key";

    /**
     * @param sites            only sites that should serve traffic; expired and disabled ones are
     *                         filtered out by the caller, not here
     * @param certificates     material for every site with SSL enabled
     */
    public ConfigBundle render(UUID bundleId,
                               UUID nginxInstanceId,
                               long sequence,
                               List<ProxySite> sites,
                               CertificateMaterialProvider certificates,
                               String actor,
                               Instant now) {

        List<ProxySite> ordered = sites.stream()
                .sorted(Comparator.comparing(site -> site.domain().value()))
                .toList();

        requireUniqueDomains(ordered);

        List<BundleFile> files = new ArrayList<>();
        files.add(BundleFile.of(BASE_FILE, renderBase()));

        Set<UUID> siteIds = new LinkedHashSet<>();
        for (ProxySite site : ordered) {
            siteIds.add(site.id());
            files.add(BundleFile.of(siteFilePath(site), renderSite(site, certificates)));
            files.addAll(renderCertificateFiles(site, certificates));
        }

        String contentHash = hashOf(files);
        return new ConfigBundle(bundleId, nginxInstanceId, sequence, contentHash, files, siteIds,
                BundleStatus.RENDERED, actor, now);
    }

    /** Renders one site in isolation, for the preview endpoint. */
    public String renderSitePreview(ProxySite site, CertificateMaterialProvider certificates) {
        return renderSite(site, certificates);
    }

    // ---- files -------------------------------------------------------------

    private static String siteFilePath(ProxySite site) {
        return "conf.d/" + site.domain().value() + ".conf";
    }

    /**
     * Bundle-wide directives: the WebSocket upgrade map, and the catch-all server.
     *
     * <p>Both are emitted once per bundle rather than per site. A duplicate map fails validation,
     * and a second default server would too.
     *
     * <p>The catch-all matters more than it looks. Without an explicit {@code default_server},
     * NGINX treats the first server block it loaded as the default, so a request whose Host
     * matches nothing is quietly proxied to whichever site sorts first. Two consequences follow,
     * and both are serious: an expired or deleted domain keeps working, so expiry has no effect a
     * client can observe; and anyone who points a DNS name at this address reaches another site's
     * backend. Answering 404 to unmatched hosts is what makes "this host serves exactly the sites
     * we configured" true.
     *
     * <p>There is one on 443 as well, and it needs a certificate to exist at all. The agent
     * generates a self-signed one carrying no subject alternative names, so it validates for
     * nothing: an unserved name reached over HTTPS gets a certificate error. That is the correct
     * answer, and far better than the alternative it replaces — presenting a real site's
     * certificate, and its content, to a domain that site does not own.
     */
    private String renderBase() {
        return """
                # Generated by %s. Do not edit; changes are overwritten on the next deployment.

                # WebSocket upgrade handling. NGINX needs Connection: upgrade only when the client
                # asked for it, and Connection: close otherwise, which a map expresses exactly.
                map $http_upgrade $connection_upgrade {
                    default upgrade;
                    ''      close;
                }

                # Catch-all. Without this, NGINX would use the first server block as the default
                # and proxy unmatched hosts to it: an expired domain would keep working, and any
                # name pointed at this address would reach a backend it was never meant to.
                #
                # It still answers ACME challenges, so a certificate can be issued for a domain
                # before any site is configured for it — which is the ordinary case, since a site
                # cannot be deployed with SSL until its certificate exists.
                server {
                    listen 80 default_server;
                    server_name _;

                    location ^~ /.well-known/acme-challenge/ {
                        alias %s;
                        default_type "text/plain";
                        try_files $uri =404;
                    }

                    location / {
                        return 404;
                    }
                }

                # The same guarantee on 443. Its certificate is valid for no name, so a client
                # reaching an unserved domain over HTTPS is told the certificate does not match
                # rather than being handed another site's response.
                #
                # ssl_reject_handshake would be tidier, but it is 1.19.4+ and this must render for
                # whatever the host runs; a certificate that validates for nothing achieves the
                # same outcome on every version.
                server {
                    listen 443 ssl default_server;
                    http2 on;
                    server_name _;

                    ssl_certificate     %s;
                    ssl_certificate_key %s;

                    return 404;
                }
                """.formatted(GENERATED_BY, ACME_CHALLENGE_ROOT, DEFAULT_TLS_CERT, DEFAULT_TLS_KEY);
    }

    private List<BundleFile> renderCertificateFiles(ProxySite site, CertificateMaterialProvider certificates) {
        if (!site.spec().sslEnabled()) {
            return List.of();
        }
        RenderedCertificate material = requireCertificate(site, certificates);
        String directory = "certs/" + site.domain().value() + "/";
        return List.of(
                BundleFile.of(directory + "fullchain.pem", material.fullChainPem()),
                BundleFile.sensitive(directory + "privkey.pem", material.privateKeyPem()));
    }

    private RenderedCertificate requireCertificate(ProxySite site, CertificateMaterialProvider certificates) {
        UUID certificateId = site.spec().sslCertificateId();
        return certificates.materialFor(certificateId)
                .orElseThrow(() -> new ValidationException("sslCertificateId",
                        "No certificate material is available for " + site.domain().value()
                                + ". The site cannot be deployed with SSL enabled until its certificate is issued."));
    }

    // ---- one site ----------------------------------------------------------

    private String renderSite(ProxySite site, CertificateMaterialProvider certificates) {
        ProxySiteSpec spec = site.spec();
        StringBuilder out = new StringBuilder(1024);

        out.append("# Generated by ").append(GENERATED_BY).append(". Do not edit.\n");
        out.append("# site ").append(site.id()).append('\n');
        out.append("# domain ").append(spec.domain().value()).append('\n');
        if (spec.window().hasExpiry()) {
            out.append("# expires ").append(spec.window().expiresAt()).append('\n');
        }
        out.append('\n');

        appendUpstream(out, site);

        if (spec.sslEnabled()) {
            // Resolve before emitting anything, so a missing certificate fails the render rather
            // than producing half a file.
            RenderedCertificate material = requireCertificate(site, certificates);
            if (spec.forceHttps()) {
                appendRedirectServer(out, site);
            } else {
                // Without forceHttps the site answers on both ports. Rendering only the TLS server
                // left port 80 to the catch-all, so the domain returned 404 over HTTP — neither
                // served nor redirected, which is what no operator turning a redirect off means.
                appendServer(out, site, false, null);
                out.append('\n');
            }
            appendServer(out, site, true, material);
        } else {
            appendServer(out, site, false, null);
        }

        return out.toString();
    }

    private void appendUpstream(StringBuilder out, ProxySite site) {
        ProxySiteSpec spec = site.spec();
        out.append("upstream ").append(upstreamName(site)).append(" {\n");

        switch (spec.loadBalancingMethod()) {
            case LEAST_CONN -> out.append("    least_conn;\n");
            case IP_HASH -> out.append("    ip_hash;\n");
            case ROUND_ROBIN -> {
                // The default. Stated explicitly so a reader of the generated file does not have
                // to know which method NGINX assumes.
                out.append("    # round robin (NGINX default)\n");
            }
        }

        List<UpstreamTarget> upstreams = spec.upstreams();
        for (UpstreamTarget upstream : upstreams) {
            out.append("    server ").append(upstream.authority());
            if (upstream.weight() != 1) {
                out.append(" weight=").append(upstream.weight());
            }
            // Passive health checking: NGINX Open Source has no active probes, so max_fails and
            // fail_timeout are the whole of what is available here.
            out.append(" max_fails=").append(upstream.maxFails());
            out.append(" fail_timeout=").append(upstream.failTimeoutSeconds()).append('s');
            if (upstream.backup()) {
                out.append(" backup");
            }
            out.append(";\n");
        }

        out.append("    keepalive 32;\n");
        out.append("}\n\n");
    }

    private void appendRedirectServer(StringBuilder out, ProxySite site) {
        out.append("server {\n");
        out.append("    listen 80;\n");
        out.append("    server_name ").append(site.domain().value()).append(";\n\n");
        // Before the redirect, or renewals break: an authority fetches the challenge over plain
        // HTTP and does not follow a redirect to HTTPS. A site with force_https would then be
        // unable to renew the very certificate that made it HTTPS in the first place.
        appendAcmeChallengeLocation(out);
        out.append("    location / {\n");
        out.append("        return 301 https://$host$request_uri;\n");
        out.append("    }\n");
        out.append("}\n\n");
    }

    /**
     * Serves HTTP-01 challenge responses.
     *
     * <p>{@code ^~} so it wins over any regex location, and {@code alias} so the token maps
     * straight onto the file the agent wrote.
     */
    private void appendAcmeChallengeLocation(StringBuilder out) {
        out.append("    location ^~ /.well-known/acme-challenge/ {\n");
        out.append("        alias ").append(ACME_CHALLENGE_ROOT).append(";\n");
        out.append("        default_type \"text/plain\";\n");
        out.append("        try_files $uri =404;\n");
        out.append("    }\n\n");
    }

    private void appendServer(StringBuilder out, ProxySite site, boolean ssl, RenderedCertificate material) {
        ProxySiteSpec spec = site.spec();

        out.append("server {\n");
        if (ssl) {
            out.append("    listen 443 ssl;\n");
            out.append("    http2 on;\n");
        } else {
            out.append("    listen 80;\n");
        }
        // IPv6 listeners are deliberately not emitted. `nginx -t` does not bind sockets, so a
        // `listen [::]` on a host without IPv6 passes validation and then fails at reload, which
        // is precisely the failure mode this platform exists to prevent. It belongs to a
        // per-instance capability flag, not to every rendered site.
        out.append("    server_name ").append(spec.domain().value()).append(";\n\n");

        if (ssl) {
            String directory = "/etc/nginx/enginx/current/certs/" + spec.domain().value();
            out.append("    ssl_certificate     ").append(directory).append("/fullchain.pem;\n");
            out.append("    ssl_certificate_key ").append(directory).append("/privkey.pem;\n");
            out.append("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            out.append("    ssl_prefer_server_ciphers off;\n");
            out.append("    ssl_session_cache shared:SSL:10m;\n");
            out.append("    ssl_session_timeout 1d;\n");
            if (spec.hstsEnabled()) {
                out.append("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n");
            }
            out.append('\n');
        }

        out.append("    client_max_body_size ").append(spec.timeouts().maxBodySizeBytes()).append(";\n\n");

        if (!ssl) {
            // Only on the plain-HTTP server. An authority validating HTTP-01 connects on port 80,
            // and a site that is already HTTPS-only serves the challenge from its redirect server.
            appendAcmeChallengeLocation(out);
        }

        appendResponseHeaders(out, spec);

        List<LocationRule> locations = spec.locations();
        for (int i = 0; i < locations.size(); i++) {
            if (i > 0) {
                out.append('\n');
            }
            appendLocation(out, site, locations.get(i));
        }

        out.append("}\n");
    }

    private void appendResponseHeaders(StringBuilder out, ProxySiteSpec spec) {
        List<ProxySiteHeader> responseHeaders = spec.headers().stream()
                .filter(header -> header.direction() == HeaderDirection.RESPONSE)
                .sorted(Comparator.comparing(ProxySiteHeader::name))
                .toList();

        if (responseHeaders.isEmpty()) {
            return;
        }
        for (ProxySiteHeader header : responseHeaders) {
            out.append("    add_header ").append(header.name())
                    .append(" \"").append(header.value()).append("\" always;\n");
        }
        out.append('\n');
    }

    private void appendLocation(StringBuilder out, ProxySite site, LocationRule location) {
        ProxySiteSpec spec = site.spec();
        String matcher = location.matchType() == LocationMatchType.EXACT ? "= " : "";

        out.append("    location ").append(matcher).append(location.pathPattern()).append(" {\n");
        out.append("        proxy_pass ").append(spec.upstreams().getFirst().scheme())
                .append("://").append(upstreamName(site)).append(";\n\n");

        out.append("        proxy_set_header Host              $host;\n");
        out.append("        proxy_set_header X-Real-IP         $remote_addr;\n");
        out.append("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n");
        out.append("        proxy_set_header X-Forwarded-Proto $scheme;\n");
        out.append("        proxy_set_header X-Forwarded-Host  $host;\n");

        out.append('\n');
        // HTTP/1.1 is required for the upstream keepalive pool to be used at all. The Connection
        // header must then be managed explicitly: cleared normally, so it is not forwarded and
        // does not close the pooled connection, or mapped for a WebSocket upgrade.
        out.append("        proxy_http_version 1.1;\n");
        if (spec.websocketEnabled()) {
            out.append("        proxy_set_header Upgrade    $http_upgrade;\n");
            out.append("        proxy_set_header Connection $connection_upgrade;\n");
        } else {
            out.append("        proxy_set_header Connection \"\";\n");
        }

        List<ProxySiteHeader> requestHeaders = spec.headers().stream()
                .filter(header -> header.direction() == HeaderDirection.REQUEST)
                .sorted(Comparator.comparing(ProxySiteHeader::name))
                .toList();
        if (!requestHeaders.isEmpty()) {
            out.append('\n');
            for (ProxySiteHeader header : requestHeaders) {
                out.append("        proxy_set_header ").append(header.name())
                        .append(" \"").append(header.value()).append("\";\n");
            }
        }

        out.append('\n');
        out.append("        proxy_connect_timeout ").append(spec.timeouts().connectSeconds()).append("s;\n");
        out.append("        proxy_send_timeout    ").append(spec.timeouts().sendSeconds()).append("s;\n");
        out.append("        proxy_read_timeout    ").append(spec.timeouts().readSeconds()).append("s;\n");
        out.append("    }\n");
    }

    // ---- naming and hashing ------------------------------------------------

    /**
     * A stable, collision-free upstream identifier.
     *
     * <p>Substituting dots for underscores alone is not enough: {@code a-b.com} and {@code a.b.com}
     * would both become {@code a_b_com} and NGINX would reject the duplicate. A short digest of
     * the original domain disambiguates them while keeping the name readable.
     */
    static String upstreamName(ProxySite site) {
        String domain = site.domain().value();
        String sanitised = domain.replace('.', '_').replace('-', '_').toLowerCase(Locale.ROOT);
        return "enginx_" + sanitised + "_" + BundleFile.digest(domain).substring(0, 6);
    }

    private static void requireUniqueDomains(List<ProxySite> sites) {
        Set<String> seen = new LinkedHashSet<>();
        for (ProxySite site : sites) {
            if (!seen.add(site.domain().value())) {
                // NGINX would accept two matching server_name blocks and silently serve the
                // first, which is far worse than refusing to render.
                throw new ValidationException("domain",
                        "Two sites on this instance both serve " + site.domain().value());
            }
        }
    }

    /**
     * Hashes the file list, not the concatenated content, so that renaming a file changes the
     * hash even when its bytes are unchanged.
     */
    private static String hashOf(List<BundleFile> files) {
        StringBuilder manifest = new StringBuilder();
        files.stream()
                .sorted(Comparator.comparing(BundleFile::path))
                .forEach(file -> manifest.append(file.path()).append(' ').append(file.sha256()).append('\n'));
        return BundleFile.digest(manifest.toString());
    }
}
